profile:
  image: 'hdphone.jpg'
  name: 'rajat srivastava'
  team: '2020 Geek Paradox'


menu:
- {name: 'About', icon: 'user', link: 'about'}
- {name: 'Professional Skills', icon: 'code', link: 'skill'}
- {name: 'Portfolio', icon: 'info', link: 'portfolio'}
- {name: 'Experience', icon: 'suitcase', link: 'experience'}
- {name: 'Education', icon: 'graduation-cap', link: 'education'}
- {name: 'Contact', icon: 'phone', link: 'contact'}

ready_pages:
  - identifier: about
    h1: who am i
  - identifier: skill
    h1: professional skills

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/evilj0ker'}
- {icon: 'facebook', link: 'https://www.facebook.com/srivrajat/'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/rajatsriv19'}
- {icon: 'github', link: 'https://github.com/rajat19'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
