profile:
  image: 'hdphone.png'
  name: 'rajat srivastava'
  team: 'Geek Paradox'

menu:
  - name: About
    identifier: about
    h1: who am i
    icon: user
  - name: Skills
    identifier: skill
    h1: professional skills
    icon: code
  - name: Projects
    identifier: projects
    h1: projects
    icon: tasks
  - name: Experience
    identifier: experience
    h1: work experience
    icon: suitcase
  - name: Education
    identifier: education
    h1: education
    icon: graduation-cap
  - name: Rewards
    identifier: rewards
    h1: rewards & recognition
    icon: trophy
  - name: Contact
    identifier: contact
    h1: contact info
    icon: phone

social:
- {icon: 'twitter', link: 'https://twitter.com/evilj0ker'}
- {icon: 'facebook-f', link: 'https://www.facebook.com/srivrajat/'}
- {icon: 'linkedin-in', link: 'https://www.linkedin.com/in/rajatsriv19'}
- {icon: 'github-alt', link: 'https://github.com/rajat19'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
